# https://github.com/dexpota/kitty-themes
include ./themes/onedark_pro.conf

shell_integration no-rc no-cursor
confirm_os_window_close 0
cursor_shape block
font_family family="JetBrainsMono Nerd Font Mono" features=""
font_size 14

initial_window_height 700
initial_window_width 1200
remember_window_size yes

cursor_blink_interval 1

tab_title_template "{tab.active_oldest_exe}"

# cursor_trail 5

map ctrl+shift+t new_tab_with_cwd
