# By Me :3
background #000000
foreground #abb2bf
selection_background #2c313a
selection_foreground #abb2bf
url_color #61afef
cursor #528bff

# Tabs
active_tab_background #1c1f24
active_tab_foreground #abb2bf
inactive_tab_background #000000
inactive_tab_foreground #5c6370
#tab_bar_background #000000

# normal
color0 #000000
color1 #ef596f
color2 #89ca78
color3 #d19a66
color4 #4d9ce0
color5 #d55fde
color6 #2bbac5
color7 #abb2bf

# bright
color8 #5c6370
color9 #f4476f
color10 #98c379
color11 #e5c07b
color12 #61afef
color13 #c678dd
color14 #4db5bd
color15 #dcdfe4

# extended colors
color16 #d19a66
color17 #ef596f
